package com.pluralsight.deli.enums;

public enum RegularTopping {
    LETTUCE, PEPPERS, ONIONS, TOMATOES, JALAPENOS, CUCUMBERS, PICKLES, GUACAMOLE, MUSHROOMS, CILANTRO, PICKLED_CARROTS, HOMEMADE_BUTTER;
}
